### ISSUE TITLE
configure() should not automatically try to authenticate on backend

### ISSUE THREAD

**Issue by Fedcomp** [lynndylanhurley/redux-auth#23] opened 2016-02-17 11:13 UTC
It's not flexible enough. Instead it should (imo) only try to authenticate when developer/component requests it. This way configure() only set endpoint url and then redux-auth itself saves user (in any login action) to localStorage with token + token_expire_time.
Right now, redux-auth spams unnecessary authentification event on every page load, not to say it's not even working at this moment. And stubbing "saving" functionality is very hackish now (i try to use it with redux-persist).

**Comment by lynndylanhurley** [comment] 2016-02-17 17:40
@Fedcomp - redux-auth started as something that I needed for a specific project. I plan to make this more flexible and extensible with future releases. My first priority is to make it possible to bypass the backend authentication so that this can be used on native apps. The work on this is mostly finished - I'll release it as soon as I get the time.

**Comment by lynndylanhurley** [comment] 2016-02-19 20:06
This is a duplicate of #7.

**Closed by lynndylanhurley** 2016-02-19 20:06 UTC

**Comment by Fedcomp** [comment] 2016-02-20 08:35
It is complete different issues. In #7 you are asked for client side localstorage support. Here i ask to separate two actions, the `configure()` endpoint, and sending request to reauthenticate.
Right now `configure()` automatically send request and there's no way to prevent that automatic request.

**Comment by lynndylanhurley** [comment] 2016-02-20 20:00
@Fedcomp - the title of the issue is "Client-only (non-universal) support". In order to accomplish this, I will need to separate the `configure` and `validate` phases. 

So you're right in that I shouldn't have called this issue a "duplicate". What I meant to say is that this issue will be resolved when #7 is resolved.
