### ISSUE TITLE
Warning on Critical Dependency

### ISSUE THREAD

**Issue by tarkanlar** [lynndylanhurley/redux-auth#9] opened 2015-12-19 17:05 UTC
I built brand new project with a starter kit after adding EmailSignupForm (or any other) i am getting this error
material-ui-theme.js?0449:1 Uncaught TypeError: Cannot read property 'getIn' of undefined

And on my console
WARNING in ./~/encoding/lib/encoding.js
Critical dependencies:
9:12-34 the request of a dependency is an expression
 @ ./~/encoding/lib/encoding.js 9:12-34

**Comment by lynndylanhurley** [comment] 2015-12-21 18:09
Hi @tarkanlar - thanks for taking the time to report this.

Two questions:

1. Is this just a warning, or is something noticeably breaking?
1. Does this happen with the other themes as well, or just material-ui?

**Comment by tarkanlar** [comment] 2015-12-21 20:51
Hi @lynndylanhurley  thanks for reply, 
1- I tried with https://github.com/erikras/react-redux-universal-hot-example and  https://github.com/davezuko/react-redux-starter-kit
2- It was just warning 
3- I tried with all themes and got the same error.

**Comment by lynndylanhurley** [comment] 2015-12-21 21:58
Thanks @tarkanlar, I'll investigate ASAP!

**Comment by baopham** [comment] 2015-12-26 02:55
@lynndylanhurley if you replace `import fetch from "node-fetch";` with `import fetch from "isomorphic-fetch";` in https://github.com/lynndylanhurley/redux-auth/blob/master/src/utils/verify-auth.js#L1, it will work.

We get that warning when it tries to load `node-fetch` who depends on `encoding` for client code.

**Comment by lynndylanhurley** [comment] 2016-01-02 07:42
Thanks @baopham - I'll add that fix to the next release.

**Comment by thomasMary** [comment] 2016-01-04 21:37
Hi @lynndylanhurley, I'm facing the same issue. Any update on the fix ?

**Comment by JonathanWi** [comment] 2016-01-04 21:46
+1 same error here, the node-fetch fix doesn't do the trick for me.

**Comment by baopham** [comment] 2016-01-04 21:48
strange, it works for me. Did you compile the code after changing the `node-fetch` line?

**Comment by JonathanWi** [comment] 2016-01-04 21:48
Reloading `npm start` or...?

**Comment by baopham** [comment] 2016-01-04 21:50
no compile `redux-auth`. Or manually replace `node-fetch` with `isomorphic-fetch`  in: https://raw.githubusercontent.com/lynndylanhurley/redux-auth/master/index.js

**Comment by JonathanWi** [comment] 2016-01-04 21:55
Could you give me a gist of your fixed and compiled index.js? I can't seem to be able to compile... Thanks a lot for your help!

**Comment by baopham** [comment] 2016-01-04 21:58
Can you try to replace `node_modules/redux-auth/index.js` with this gist: https://gist.github.com/baopham/6f6ec3ac707f0838dfa3

All I did was just find and replace `node-fetch` in the file.

**Comment by JonathanWi** [comment] 2016-01-04 22:01
Yeah, just tried replacing it manually too in `node_modules/redux-auth/index.js`, but I'm still prompted with : 
```
Uncaught TypeError: Cannot read property 'getIn' of undefined
```
Any idea?

**Comment by baopham** [comment] 2016-01-04 22:06
That is a different error than the original poster's error though. Or do you mean you only get that error after replacing the file? Btw, did you setup the reducer: 

```
import {authStateReducer} from "redux-auth";
// create your main reducer
const reducer = combineReducers({
  auth: authStateReducer,
  // ... add your own reducers here
});
```

**Comment by JonathanWi** [comment] 2016-01-04 22:10
Hey @baopham thanks it worked!

Regarding the error, it is the same one that stated by the original poster:

> I built brand new project with a starter kit after adding EmailSignupForm (or any other) i am getting this error
material-ui-theme.js?0449:1 Uncaught TypeError: Cannot read property 'getIn' of undefined

So switching to `isomorphic-fetch` was also needed! 

Thanks for your help, hoping for a quick fixed release,

Cheers

**Comment by baopham** [comment] 2016-01-04 22:11
@JonathanWi oh right, i only looked at the error on the console. Thanks for confirming.

**Comment by waterstar** [comment] 2016-04-05 07:41
I am sting seeing this problem with the latest code. Tried replacing "node-fetch" but no luck. Any suggestion? Thanks.

**Comment by saisasankparimi** [comment] 2016-04-13 10:18
I am still seeing this problem with the latest code.
<img width="1136" alt="screen shot 2016-04-13 at 3 46 45 pm" src="https://cloud.githubusercontent.com/assets/10138733/14490191/11425386-018f-11e6-9567-3adaaf86b4d9.png">

**Comment by owenr88** [comment] 2016-05-17 19:08
For future people... I had this error and fixed it by defining the reducer key, as pointed out by @baopham. Use `auth: authStateReducer`

**Comment by lynndylanhurley** [comment] 2016-07-17 03:51
The latest version of [the demo](https://github.com/lynndylanhurley/redux-auth-demo) is based on https://github.com/erikras/react-redux-universal-hot-example.

Can you guys please try again with the demo?
https://github.com/lynndylanhurley/redux-auth-demo

**Comment by lynndylanhurley** [comment] 2016-07-20 00:30
Closing this as I cannot reproduce. Please re-open if you have more information.

**Closed by lynndylanhurley** 2016-07-20 00:30 UTC
